
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - backend/.env
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://neondb_owner:npg_2ipfFMS9hgOy@ep-lively-field-aix68yfw.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require

  frontend:
    build: ./frontend
    env_file:
      - frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
